import type { EmojiQuestion } from '../../domain/questions'

type EmojiData = [answer: string, emojis: [string, string, string, string, ...string[]], category: 'Film' | 'Serie']

const EMOJI_DATA: EmojiData[] = [
  ['Jurassic Park', ['🦖', '🏝️', '🚙', '🧬'], 'Film'],
  ['Titanic', ['🚢', '🧊', '💎', '🌊'], 'Film'],
  ['Matrix', ['💊', '🕶️', '💻', '🐇'], 'Film'],
  ['Der weiße Hai', ['🦈', '🏖️', '🚤', '🩸'], 'Film'],
  ['Ghostbusters', ['👻', '🚫', '🏙️', '🔫'], 'Film'],
  ['Zurück in die Zukunft', ['🚗', '⚡', '🕰️', '🔥'], 'Film'],
  ['Der König der Löwen', ['🦁', '👑', '🌅', '🐗'], 'Film'],
  ['Findet Nemo', ['🐠', '🔎', '🌊', '🐢'], 'Film'],
  ['Die Eiskönigin', ['👸', '❄️', '⛄', '🏰'], 'Film'],
  ['Toy Story', ['🤠', '🚀', '🧸', '👦'], 'Film'],
  ['Der Herr der Ringe', ['💍', '🌋', '🧙', '🧝'], 'Film'],
  ['Harry Potter', ['⚡', '🧙', '🦉', '🏰'], 'Film'],
  ['Star Wars', ['🌌', '⚔️', '🤖', '🚀'], 'Film'],
  ['E.T.', ['👽', '🚲', '🌕', '☎️'], 'Film'],
  ['Kevin – Allein zu Haus', ['👦', '🏠', '🎄', '🪤'], 'Film'],
  ['Fluch der Karibik', ['🏴‍☠️', '🚢', '💀', '🧭'], 'Film'],
  ['Indiana Jones', ['🤠', '🐍', '🏺', '🗺️'], 'Film'],
  ['Batman', ['🦇', '🌃', '🤡', '🚗'], 'Film'],
  ['Superman', ['🦸', '📰', '🌆', '💎'], 'Film'],
  ['Spider-Man', ['🕷️', '🕸️', '🏙️', '🦸'], 'Film'],
  ['Iron Man', ['🤖', '❤️', '💰', '🚀'], 'Film'],
  ['The Avengers', ['🦸', '🔨', '🛡️', '💚'], 'Film'],
  ['Black Panther', ['🐈‍⬛', '👑', '💜', '🌍'], 'Film'],
  ['Joker', ['🤡', '🃏', '🕺', '🏙️'], 'Film'],
  ['Gladiator', ['⚔️', '🏛️', '🛡️', '👑'], 'Film'],
  ['Rocky', ['🥊', '🏃', '🥩', '🏆'], 'Film'],
  ['Karate Kid', ['🥋', '🪰', '🚗', '🏆'], 'Film'],
  ['Top Gun', ['✈️', '🕶️', '🏍️', '🏐'], 'Film'],
  ['Stirb langsam', ['🏢', '🎄', '👮', '💥'], 'Film'],
  ['Terminator', ['🤖', '🔫', '🕶️', '🔥'], 'Film'],
  ['Alien', ['👽', '🚀', '🥚', '😱'], 'Film'],
  ['Predator', ['👽', '🌴', '🔫', '👁️'], 'Film'],
  ['Shining', ['🏨', '🪓', '❄️', '👯'], 'Film'],
  ['Es', ['🤡', '🎈', '🚲', '🌧️'], 'Film'],
  ['Scream', ['😱', '☎️', '🔪', '🎭'], 'Film'],
  ['Psycho', ['🚿', '🔪', '🏨', '👩'], 'Film'],
  ['Der Pate', ['🤵', '🌹', '🔫', '🐴'], 'Film'],
  ['Pulp Fiction', ['💼', '🍔', '💃', '🔫'], 'Film'],
  ['Fight Club', ['🥊', '🧼', '🏢', '🤫'], 'Film'],
  ['Forrest Gump', ['🏃', '🍫', '🪶', '🚌'], 'Film'],
  ['Cast Away', ['🏝️', '🏐', '✈️', '🔥'], 'Film'],
  ['Die Truman Show', ['📺', '🌊', '🚪', '☀️'], 'Film'],
  ['Und täglich grüßt das Murmeltier', ['⏰', '🐿️', '❄️', '🔁'], 'Film'],
  ['Pretty Woman', ['👠', '💎', '🏨', '❤️'], 'Film'],
  ['Dirty Dancing', ['💃', '🍉', '🏨', '❤️'], 'Film'],
  ['La La Land', ['🎹', '💃', '🌃', '⭐'], 'Film'],
  ['Mamma Mia!', ['🏝️', '🎶', '👰', '🇬🇷'], 'Film'],
  ['Grease', ['🚗', '🎶', '💃', '🏫'], 'Film'],
  ['The Sound of Music', ['🏔️', '🎶', '👨‍👩‍👧‍👦', '🇦🇹'], 'Film'],
  ['Der Zauberer von Oz', ['🌪️', '👠', '🦁', '🌈'], 'Film'],
  ['Alice im Wunderland', ['🐇', '🫖', '♥️', '🕳️'], 'Film'],
  ['Charlie und die Schokoladenfabrik', ['🍫', '🏭', '🎩', '🎫'], 'Film'],
  ['Die Tribute von Panem', ['🏹', '🔥', '🐦', '🏟️'], 'Film'],
  ['Twilight', ['🧛', '🐺', '🌲', '❤️'], 'Film'],
  ['Avatar', ['🔵', '🌳', '🏹', '🪐'], 'Film'],
  ['Inception', ['💤', '🌀', '🏙️', '🪀'], 'Film'],
  ['Interstellar', ['🚀', '🌽', '🕳️', '⌚'], 'Film'],
  ['Der Marsianer', ['🔴', '🥔', '🚀', '📡'], 'Film'],
  ['Gravity', ['👩‍🚀', '🌍', '🛰️', '🧯'], 'Film'],
  ['Oben', ['🎈', '🏠', '👴', '🐕'], 'Film'],
  ['Breaking Bad', ['👨‍🏫', '⚗️', '💵', '🚐'], 'Serie'],
  ['Game of Thrones', ['🐉', '👑', '⚔️', '❄️'], 'Serie'],
  ['Friends', ['☕', '🛋️', '👫', '🏙️'], 'Serie'],
  ['Stranger Things', ['🚲', '🧇', '👾', '🔦'], 'Serie'],
  ['The Office', ['🏢', '📄', '☕', '📎'], 'Serie'],
  ['Die Simpsons', ['🍩', '💛', '☢️', '📺'], 'Serie'],
  ['House of the Dragon', ['🐉', '🏰', '🔥', '👑'], 'Serie'],
  ['The Walking Dead', ['🧟', '🏹', '🧠', '🛣️'], 'Serie'],
  ['The Mandalorian', ['🚀', '🪖', '👶', '🌌'], 'Serie'],
  ['Squid Game', ['🦑', '🔺', '🟢', '💰'], 'Serie'],
  ['Haus des Geldes', ['🎭', '🏦', '💶', '🔴'], 'Serie'],
  ['Sherlock', ['🔎', '🎻', '🧥', '🇬🇧'], 'Serie'],
  ['Doctor Who', ['📞', '⏳', '👽', '🇬🇧'], 'Serie'],
  ['Black Mirror', ['📱', '🪞', '🤖', '😨'], 'Serie'],
  ['Wednesday', ['🖤', '🖐️', '🏫', '🕷️'], 'Serie'],
  ['Bridgerton', ['👗', '💌', '👑', '🐝'], 'Serie'],
  ['The Crown', ['👑', '🇬🇧', '🏰', '📺'], 'Serie'],
  ['Narcos', ['💊', '💵', '🇨🇴', '👮'], 'Serie'],
  ['Peaky Blinders', ['🧢', '🥃', '🐎', '🔪'], 'Serie'],
  ['Vikings', ['🛡️', '⚔️', '🚢', '🪓'], 'Serie'],
  ['Lost', ['✈️', '🏝️', '🐻‍❄️', '🔢'], 'Serie'],
  ['Dexter', ['🩸', '🔪', '🧪', '🌴'], 'Serie'],
  ['Dr. House', ['🩺', '💊', '🦯', '🏥'], 'Serie'],
  ['Grey’s Anatomy', ['🏥', '🩺', '❤️', '🚑'], 'Serie'],
  ['The Big Bang Theory', ['🧪', '🚀', '🥡', '🤓'], 'Serie'],
  ['How I Met Your Mother', ['🍺', '☂️', '🎺', '👫'], 'Serie'],
  ['Modern Family', ['👨‍👩‍👧‍👦', '🏠', '📹', '😂'], 'Serie'],
  ['South Park', ['🏔️', '🧢', '❄️', '😂'], 'Serie'],
  ['Futurama', ['🚀', '🤖', '🍕', '👽'], 'Serie'],
  ['Rick and Morty', ['🧪', '🌀', '👴', '👦'], 'Serie'],
  ['Akte X', ['👽', '🔦', '🛸', '📁'], 'Serie'],
  ['Twin Peaks', ['☕', '🥧', '🌲', '🦉'], 'Serie'],
  ['Baywatch', ['🏖️', '🛟', '🏃', '🌊'], 'Serie'],
  ['Knight Rider', ['🚗', '🤖', '⌚', '🕶️'], 'Serie'],
  ['Das A-Team', ['🚐', '💥', '🪖', '🔧'], 'Serie'],
  ['MacGyver', ['📎', '🔧', '💥', '🧠'], 'Serie'],
  ['Star Trek', ['🖖', '🚀', '🌌', '👽'], 'Serie'],
  ['Gilmore Girls', ['☕', '📚', '👩‍👧', '🍂'], 'Serie'],
  ['Sex and the City', ['👠', '🍸', '🗽', '👜'], 'Serie'],
  ['Die Sopranos', ['🤵', '🍝', '🔫', '🦆'], 'Serie'],
]

export const EMOJI_QUESTIONS: EmojiQuestion[] = EMOJI_DATA.map(([answer, emojis, category], index) => ({
  id: `emoji-${String(index + 1).padStart(3, '0')}`,
  type: 'emoji',
  prompt: category === 'Film' ? 'Welcher Film ist dargestellt?' : 'Welche Serie ist dargestellt?',
  answer,
  category,
  difficulty: (1 + (index % 3)) as 1 | 2 | 3,
  emojis,
}))