import type { QuizQuestion } from '../domain/questions'
import { COUNTRY_LIE_QUESTIONS, COUNTRY_PICTURE_QUESTIONS } from './pools/countryQuestions'
import { EMOJI_QUESTIONS } from './pools/emojiQuestions'
import { SOUND_QUESTIONS } from './pools/soundQuestions'
import { THEMED_QUESTIONS } from './pools/themedQuestions'
import { WHO_AM_I_QUESTIONS } from './pools/whoAmIQuestions'

const DEMO_QUESTIONS: QuizQuestion[] = [
  {
    id: 'picture-flag-portugal',
    type: 'picture',
    prompt: 'Zu welchem Land gehört diese Flagge?',
    answer: 'Portugal',
    category: 'Flaggen',
    difficulty: 1,
    imageUrl: `${import.meta.env.BASE_URL}media/images/flags/pt.svg`,
    imageAlt: 'Flagge mit grünem und rotem Feld und einem Wappen',
    source: 'Flagcdn / Wikimedia Commons',
  },
  {
    id: 'picture-flag-japan',
    type: 'picture',
    prompt: 'Zu welchem Land gehört diese Flagge?',
    answer: 'Japan',
    category: 'Flaggen',
    difficulty: 1,
    imageUrl: `${import.meta.env.BASE_URL}media/images/flags/jp.svg`,
    imageAlt: 'Weiße Flagge mit rotem Kreis',
    source: 'Flagcdn / Wikimedia Commons',
  },
  {
    id: 'picture-flag-south-africa',
    type: 'picture',
    prompt: 'Zu welchem Land gehört diese Flagge?',
    answer: 'Südafrika',
    acceptedAnswers: ['Republik Südafrika'],
    category: 'Flaggen',
    difficulty: 2,
    imageUrl: `${import.meta.env.BASE_URL}media/images/flags/za.svg`,
    imageAlt: 'Mehrfarbige Flagge mit grünem Y',
    source: 'Flagcdn / Wikimedia Commons',
  },
  {
    id: 'who-curie',
    type: 'who-am-i',
    prompt: 'Welche Person wird gesucht?',
    answer: 'Marie Curie',
    category: 'Wissenschaft',
    difficulty: 2,
    hints: [
      'Ich wurde 1867 in Warschau geboren.',
      'Meine Forschung veränderte unser Verständnis von Radioaktivität.',
      'Ich erhielt Nobelpreise in zwei verschiedenen Naturwissenschaften.',
      'Das Element Curium trägt den Namen meiner Familie.',
    ],
  },
  {
    id: 'who-bowie',
    type: 'who-am-i',
    prompt: 'Welche Person wird gesucht?',
    answer: 'David Bowie',
    category: 'Musik',
    difficulty: 2,
    hints: [
      'Ich wurde 1947 in London geboren.',
      'Eine meiner Kunstfiguren kam vom Mars.',
      'Ich spielte einen Koboldkönig im Film Labyrinth.',
      'Space Oddity und Heroes gehören zu meinen bekanntesten Liedern.',
    ],
  },
  {
    id: 'who-kahlo',
    type: 'who-am-i',
    prompt: 'Welche Person wird gesucht?',
    answer: 'Frida Kahlo',
    category: 'Kunst',
    difficulty: 2,
    hints: [
      'Ich wurde 1907 in Coyoacán geboren.',
      'Viele meiner Werke sind Selbstporträts.',
      'Ein schwerer Busunfall prägte mein Leben und meine Kunst.',
      'Ich war mit dem Maler Diego Rivera verheiratet.',
    ],
  },
  {
    id: 'themed-europe-capital',
    type: 'themed',
    prompt: 'Welche europäische Hauptstadt liegt an der Moldau?',
    answer: 'Prag',
    category: 'Geografie',
    theme: 'Europa',
    difficulty: 1,
  },
  {
    id: 'themed-cocktail-mule',
    type: 'themed',
    prompt: 'Welche Spirituose bildet die Basis eines Moscow Mule?',
    answer: 'Wodka',
    category: 'Getränke',
    theme: 'Cocktails',
    difficulty: 1,
  },
  {
    id: 'themed-sailing-port',
    type: 'themed',
    prompt: 'Wie heißt die linke Seite eines Schiffs in Fahrtrichtung?',
    answer: 'Backbord',
    category: 'Sport',
    theme: 'Segeln',
    difficulty: 1,
  },
  {
    id: 'lie-octopus',
    type: 'lie-detector',
    prompt: 'Welche Aussage über Kraken ist gelogen?',
    answer: 'Aussage 3',
    category: 'Natur',
    difficulty: 2,
    statements: [
      'Kraken besitzen drei Herzen.',
      'Ihr Blut erscheint durch Hämocyanin blau.',
      'Sie besitzen ein starres Innenskelett.',
    ],
    lieIndex: 2,
    explanation: 'Kraken sind wirbellose Tiere und besitzen kein starres Innenskelett.',
  },
  {
    id: 'lie-eiffel',
    type: 'lie-detector',
    prompt: 'Welche Aussage über den Eiffelturm ist gelogen?',
    answer: 'Aussage 2',
    category: 'Bauwerke',
    difficulty: 2,
    statements: [
      'Er wurde für die Weltausstellung 1889 errichtet.',
      'Gustave Eiffel entwarf ihn ganz allein.',
      'Seine Höhe verändert sich durch Wärmeausdehnung.',
    ],
    lieIndex: 1,
    explanation: 'Die Ingenieure Maurice Koechlin und Émile Nouguier entwickelten den grundlegenden Entwurf.',
  },
  {
    id: 'lie-honey',
    type: 'lie-detector',
    prompt: 'Welche Aussage über Honig ist gelogen?',
    answer: 'Aussage 1',
    category: 'Essen',
    difficulty: 2,
    statements: [
      'Honig muss immer im Kühlschrank gelagert werden.',
      'Sein geringer Wassergehalt hemmt viele Mikroorganismen.',
      'Kristallisierter Honig ist weiterhin essbar.',
    ],
    lieIndex: 0,
    explanation: 'Honig sollte trocken und bei Raumtemperatur lagern; ein Kühlschrank ist nicht nötig.',
  },
  {
    id: 'sound-trex',
    type: 'sound',
    prompt: 'Welches Wesen hörst du?',
    answer: 'Ein Dinosaurier / T-Rex',
    acceptedAnswers: ['Dinosaurier', 'T-Rex', 'Tyrannosaurus Rex'],
    category: 'Tierstimmen',
    difficulty: 1,
    media: {
      kind: 'audio',
      url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-audio/t-rex-roar.mp3',
    },
    source: 'MDN Web Docs, CC0-Audio',
  },
  {
    id: 'emoji-jurassic-park',
    type: 'emoji',
    prompt: 'Welcher Film ist dargestellt?',
    answer: 'Jurassic Park',
    category: 'Film',
    difficulty: 1,
    emojis: ['🦖', '🏝️', '🚙', '🧬'],
  },
  {
    id: 'emoji-titanic',
    type: 'emoji',
    prompt: 'Welcher Film ist dargestellt?',
    answer: 'Titanic',
    category: 'Film',
    difficulty: 1,
    emojis: ['🚢', '🧊', '💎', '🌊'],
  },
  {
    id: 'emoji-breaking-bad',
    type: 'emoji',
    prompt: 'Welche Serie ist dargestellt?',
    answer: 'Breaking Bad',
    category: 'Serie',
    difficulty: 2,
    emojis: ['👨‍🏫', '⚗️', '💵', '🚐'],
  },
]

export const RETIRED_SEED_IDS = DEMO_QUESTIONS
  .map((question) => question.id)

export const SEED_QUESTIONS: QuizQuestion[] = [
  ...COUNTRY_PICTURE_QUESTIONS,
  ...WHO_AM_I_QUESTIONS,
  ...SOUND_QUESTIONS,
  ...THEMED_QUESTIONS,
  ...COUNTRY_LIE_QUESTIONS,
  ...EMOJI_QUESTIONS,
]